### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by chrispazz** [whoinow/wled-ha-rgb#2]
Hello,
I installed your server (UI version) on the same Hyperion linux debian host (with root user).
It connects to home assistant getting entities but Hyperion can't access to wled configurations.

Opening with browser (I have port 80 for wled) I'm getting

Cannot GET /

Thank you
C

**Comment by whoinow** [comment]
Hey Chris,
What exactly is the issue? Hyperion can't connect to the wled-ha-rgb instance? Is port 80 configured for wled-ha-rgb?

**Comment by whoinow** [comment]
wled-ha-rgb UI runs on port 3299, the port for WLED is configured there and defaults to 8989 in the WLED HTTP Port setting. DId you change the WLED HTTP Port to 80?

**Comment by chrispazz** [comment]
Yes I did...
The setup web interface is running ok (and it gets HA entities correctly)....

**Comment by whoinow** [comment]
I just pushed a possible fix to the add-ui branch. Let me know if that works for you.

**Comment by whoinow** [comment]
Looks like more changes are needed, I will look into later today.

**Comment by whoinow** [comment]
Ok, just pushed another change, let me know if that works.

**Comment by chrispazz** [comment]
Hi, just tried:

When connecting to HA it retrieves the led lights correctly but when pushing send config  and restart I get:

TypeError: Cannot read properties of undefined (reading '0')
    at /home/pi/wled-ha-rgb-add-ui/ui/server.js:52:26
    at Layer.handle [as handle_request] (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/index.js:346:12)
    at next (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/index.js:175:3)
    at router (/home/pi/wled-ha-rgb-add-ui/ui/node_modules/express/lib/router/index.js:47:12)

**Comment by whoinow** [comment]
Delete your config.json. However its still broken. I keep finding more changes that need to be handled. I will update when I can get through it all and tested working.

**Comment by whoinow** [comment]
So I can't confirm it right now, but from what I have seen so far, there appears to be a bug in Hyperion in how it determines the UDP protocol for WLED. Specifically if its determined to be RAW on the web server, it doens't make it into the C++ code. So I need to confirm that somehow and get a bug into Hyperion or start supporting the DDP UDP protocol. Either will take time obviously.

**Comment by chrispazz** [comment]
Hi, yes you are right....it is a pity...let's hope that they solve the RAW protocol so that you do not have to change your code...

Thank you!

**Comment by whoinow** [comment]
Alright, I think I have things working in the hyp2.x.x branch. Delete you config.json and give it a shot.

**Comment by chrispazz** [comment]
Superfast!
just tried but I see that connecting to HA does not retrieve all my RGB lights (also no WLED) but I list only my led that HA gets from the Hyperion integration. Do you apply any filter when getting entities from HA? does it not get all light type entities?

Also I noticed that when saving parameters from web configuration, it does not keep the HA address (I do not use homeassistant.local but IP address).....

**Comment by whoinow** [comment]
The RGB lights can only be RGB, not RGBW, RGBWW, etc. I can look into supporting this, but its not super straight forward when all I get is RGB data from Hyperion. I also don't have any RGBW(*) lights to test with.

The HASS host was being correctly saved to the config, just not updated in the UI on a refresh. I just pushed a fixed for this.

**Comment by chrispazz** [comment]
I am trying to use some Tuya spot lights.
Here it is what HA tell me about them:

min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list:
  - Scene
  - Music
supported_color_modes:
  - color_temp
  - hs
scene_data: 000e0d0000000000000000c80000
friendly_name: TL_SALA SPOT 1
supported_features: 4

They are RGBCW but I think that, also with not good white, it could be possible to use only RGB values.
What do you use to send HA the RGB colours?

**Comment by whoinow** [comment]
Ah ok, HS color mode. I just added a new branch that supports RGB**. I will see about HS in that branch.

**Comment by whoinow** [comment]
Alright the hyp2.x.x-rgb+ branch has HS support now. I can't really test it, so let me know. I am out of time to work on this for a bit, so report any issues and I will try to get back to you as soon as I can.

I might delete your config.json before trying just to make sure things are clean.

**Comment by whoinow** [comment]
Hey Chris. I haven't heard back, so I am going to close the issue. Feel free to reopen it if there are still issues.
